const fs = require('fs');
let content = fs.readFileSync('components/teacher/StudentManagementContent.tsx', 'utf8');
content = content.replace(/const \[locationFilter, setLocationFilter\] = useState\("all"\);\n\s*/g, '');
content = content.replace(/const \[modalLocationFilter, setModalLocationFilter\] = useState\("all"\);\n\s*/g, '');
content = content.replace(/setModalLocationFilter\("all"\);\n\s*/g, '');
content = content.replace(/const locations = useMemo\([^;]+;\n\s*/g, '');
content = content.replace(/const matchesLocation = locationFilter === "all" \|\| student\.location === locationFilter;\n\s*return matchesQuery && matchesStandard && matchesBoard && matchesLocation;/g, 'return matchesQuery && matchesStandard && matchesBoard;');
content = content.replace(/, locationFilter\]\)/g, '])');
content = content.replace(/const matchesLocation = modalLocationFilter === "all" \|\| student\.location === modalLocationFilter;\n\s*/g, '');
content = content.replace(/return matchesLocation && matchesBoard && matchesStandard;/g, 'return matchesBoard && matchesStandard;');
content = content.replace(/, modalLocationFilter/g, '');
content = content.replace(/<TableHead className="text-white">Location<\/TableHead>\n\s*/g, '');
content = content.replace(/<TableCell>\{student\.location\}<\/TableCell>\n\s*/g, '');
content = content.replace(/<div><span className="text-muted-foreground">Location:<\/span> \{selectedStudent\.location\}<\/div>\n\s*/g, '');
content = content.replace(/<TableHead>Location<\/TableHead>/g, '');
content = content.replace(/<TableCell>\{s\.location \|\| "-"}<\/TableCell>/g, '');
content = content.replace(/location: r\.location \|\| "",/g, '');
content = content.replace(/<Select value=\{locationFilter\}[\s\S]*?All Locations[\s\S]*?<\/Select>\n\s*/g, '');
content = content.replace(/<div className="space-y-1">\n\s*<Label className="text-xs text-muted-foreground">Location \(Branch\)<\/Label>\n\s*<select[\s\S]*?<\/select>\n\s*<\/div>\n\s*/g, '');
fs.writeFileSync('components/teacher/StudentManagementContent.tsx', content);
console.log('done');
